name: 'Build Linux'

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version to use'
        required: false
        default: '3.10'
        type: string
      chromium_version:
        description: 'Ungoogled Chromium version'
        required: false
        default: '129.0.6668.58-1'
        type: string
      chromedriver_version:
        description: 'ChromeDriver version'
        required: false
        default: '131.0.6724.0'
        type: string

env:
  CHROMIUM_BASE_URL: 'https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/releases/download'
  CHROMIUM_ARCHIVE_NAME: 'ungoogled-chromium.tar.xz'
  CHROMEDRIVER_BASE_URL: 'https://storage.googleapis.com/chrome-for-testing-public'
  CHROMEDRIVER_ARCHIVE_NAME: 'chromedriver.zip'
  OUTPUT_DIR: 'ungoogled_chromium'

jobs:
  build-linux:
    name: Bundle Executable
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Pipenv
        run: pip install --user pipenv

      - name: Install Python Dependencies
        run: |
          pipenv install --dev

      - name: Cache Ungoogled Chromium
        id: cache-chromium
        uses: actions/cache@v4
        with:
          path: ${{ env.OUTPUT_DIR }}
          key: ${{ runner.os }}-chromium-${{ inputs.chromium_version }}

      - name: Download Ungoogled Chromium
        if: steps.cache-chromium.outputs.cache-hit != 'true'
        run: |
          curl -L -o ${{ env.CHROMIUM_ARCHIVE_NAME }} ${{ env.CHROMIUM_BASE_URL }}/${{ inputs.chromium_version }}/ungoogled-chromium_${{ inputs.chromium_version }}_linux.tar.xz
          mkdir -p ${{ env.OUTPUT_DIR }}
          tar -xvf ${{ env.CHROMIUM_ARCHIVE_NAME }} -C ${{ env.OUTPUT_DIR }}

      - name: Cache ChromeDriver
        id: cache-chromedriver
        uses: actions/cache@v4
        with:
          path: ${{ env.OUTPUT_DIR }}/chromedriver
          key: ${{ runner.os }}-chromedriver-${{ inputs.chromedriver_version }}

      - name: Download ChromeDriver
        if: steps.cache-chromedriver.outputs.cache-hit != 'true'
        run: |
          curl -L -o ${{ env.CHROMEDRIVER_ARCHIVE_NAME }} ${{ env.CHROMEDRIVER_BASE_URL }}/${{ inputs.chromedriver_version }}/linux64/chromedriver-linux64.zip
          mkdir -p ${{ env.OUTPUT_DIR }}/chromedriver
          unzip ${{ env.CHROMEDRIVER_ARCHIVE_NAME }} -d ${{ env.OUTPUT_DIR }}/chromedriver

      # - name: Package the app using PyInstaller
      #   run: pipenv run pyinstaller main.spec

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Linux Executable
      #     path: dist/scrapegoat_linux
