name: '      '

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      context_path:
        required: true
        type: string
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
    secrets:
      PACKAGES_TOKEN:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push Image
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build ${{ inputs.context_path }} --tag ${{ inputs.repo }}/${{ inputs.image }}:${{ inputs.tag }} -f ${{ inputs.dockerfile_path }}
        docker push ${{ inputs.repo }}/${{ inputs.image }}:${{ inputs.tag }}