name: 'Build Linux'

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version to use'
        required: false
        default: '3.10'
        type: string
      chromium_version:
        description: 'Ungoogled Chromium version'
        required: false
        default: '129.0.6668.58-1'
        type: string

env:
  CHROMIUM_BASE_URL: 'https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/releases/download'
  CHROMIUM_ARCHIVE_NAME: 'ungoogled-chromium.tar.xz'
  OUTPUT_DIR: 'ungoogled_chromium'

jobs:
  build-linux:
    name: Bundle Executable
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Pipenv
        run: pip install --user pipenv

      - name: Install Python Dependencies
        run: |
          pipenv install --dev

      - name: Cache Ungoogled Chromium
        id: cache-chromium
        uses: actions/cache@v4
        with:
          path: ${{ env.OUTPUT_DIR }}
          key: ${{ runner.os }}-chromium-${{ inputs.chromium_version }}

      - name: Download Ungoogled Chromium
        if: steps.cache-chromium.outputs.cache-hit != 'true'
        run: |
          curl -L -o ${{ env.CHROMIUM_ARCHIVE_NAME }} ${{ env.CHROMIUM_BASE_URL }}/${{ inputs.chromium_version }}/ungoogled-chromium_${{ inputs.chromium_version }}_linux.tar.xz
          mkdir -p ${{ env.OUTPUT_DIR }}
          tar -xvf ${{ env.CHROMIUM_ARCHIVE_NAME }} -C ${{ env.OUTPUT_DIR }}

      - name: Check Chromium and ChromeDriver Version
        run: |
          if [ -f "${{ env.OUTPUT_DIR }}/ungoogled-chromium_${{ inputs.chromium_version }}_linux/chrome" ]; then
            echo "Chromium version:"
            ${{ env.OUTPUT_DIR }}/ungoogled-chromium_${{ inputs.chromium_version }}_linux/chrome --product-version
          else
            echo "Chromium executable not found"
          fi
          
          if [ -f "${{ env.OUTPUT_DIR }}/ungoogled-chromium_${{ inputs.chromium_version }}_linux/chromedriver" ]; then
            echo "ChromeDriver version:"
            ${{ env.OUTPUT_DIR }}/ungoogled-chromium_${{ inputs.chromium_version }}_linux/chromedriver --version
          else
            echo "ChromeDriver executable not found"
          fi
          
          echo "Listing contents of Chromium directory:"
          ls -l ${{ env.OUTPUT_DIR }}/ungoogled-chromium_${{ inputs.chromium_version }}_linux/

      # - name: Package the app using PyInstaller
      #   run: pipenv run pyinstaller main.spec

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Linux Executable
      #     path: dist/scrapegoat_linux
