name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  PYTHON_VERSION: '3.10'
  CHROMIUM_VERSION_LINUX: '129.0.6668.58-1'
  CHROMIUM_VERSION_MACOS_WINDOWS: '129.0.6668.58-1.1'
  CHROMEDRIVER_VERSION: '131.0.6724.0'
  DOCKER_REPO: 'ghcr.io/${{ github.repository }}'
  DOCKER_IMAGE: 'scrapegoat'
  DOCKER_CONTEXT: '.'
  DOCKER_FILE: './GoatFile'

jobs:
  build-linux:
    name: Linux x64
    uses: ./.github/workflows/build-linux.yml
    with:
      python_version: ${{ env.PYTHON_VERSION }}
      chromium_version: ${{ env.CHROMIUM_VERSION_LINUX }}
      chromedriver_version: ${{ env.CHROMEDRIVER_VERSION }}

  build-macos:
    name: macOS x64
    uses: ./.github/workflows/build-macos.yml
    with:
      python_version: ${{ env.PYTHON_VERSION }}
      chromium_version: ${{ env.CHROMIUM_VERSION_MACOS_WINDOWS }}
      chromedriver_version: ${{ env.CHROMEDRIVER_VERSION }}

  build-windows:
    name: Windows x64
    uses: ./.github/workflows/build-windows.yml
    with:
      python_version: ${{ env.PYTHON_VERSION }}
      chromium_version: ${{ env.CHROMIUM_VERSION_MACOS_WINDOWS }}
      chromedriver_version: ${{ env.CHROMEDRIVER_VERSION }}

  build-docker:
    name: Docker
    uses: ./.github/workflows/build-docker.yml
    with:
      repo: ${{ env.DOCKER_REPO }}
      context_path: ${{ env.DOCKER_CONTEXT }}
      image: ${{ env.DOCKER_IMAGE }}
      tag: ${{ github.ref_name }}
      dockerfile_path: ${{ env.DOCKER_FILE }}
    secrets:
      PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # create-release:
  #   needs: [build-linux, build-macos, build-windows, build-docker]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

      # - name: Download Linux artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: Linux Executable
      #     path: artifacts

      # - name: Download macOS artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: macOS Executable
      #     path: artifacts

      # - name: Download Windows artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: Windows Executable
      #     path: artifacts

      # - name: Read release message
      #   id: release_message
      #   run: echo "message=$(cat RELEASE_MESSAGE.md)" >> $GITHUB_OUTPUT

      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       artifacts/scrapegoat_linux
      #       artifacts/scrapegoat_macos_x64
      #       artifacts/scrapegoat_windows_x64.exe
      #     body: ${{ steps.release_message.outputs.message }}
      #     tag_name: ${{ github.ref_name }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
